// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dental_model_transfer.proto
// </auto-generated>
// Original file comments:
// Copyright 2026 The gRPC Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Dentalmodeltransfer {
  public static partial class DentalModelTransfer
  {
    static readonly string __ServiceName = "dentalmodeltransfer.DentalModelTransfer";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dentalmodeltransfer.ClientMessage> __Marshaller_dentalmodeltransfer_ClientMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dentalmodeltransfer.ClientMessage.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Dentalmodeltransfer.ServerMessage> __Marshaller_dentalmodeltransfer_ServerMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Dentalmodeltransfer.ServerMessage.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Dentalmodeltransfer.ClientMessage, global::Dentalmodeltransfer.ServerMessage> __Method_StreamDentalModel = new grpc::Method<global::Dentalmodeltransfer.ClientMessage, global::Dentalmodeltransfer.ServerMessage>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "StreamDentalModel",
        __Marshaller_dentalmodeltransfer_ClientMessage,
        __Marshaller_dentalmodeltransfer_ServerMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Dentalmodeltransfer.DentalModelTransferReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DentalModelTransfer</summary>
    [grpc::BindServiceMethod(typeof(DentalModelTransfer), "BindService")]
    public abstract partial class DentalModelTransferBase
    {
      /// <summary>
      /// Android glasses connect as the client. The C++ side streams model data back
      /// while the client can send requests and acknowledgements on the same RPC.
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task StreamDentalModel(grpc::IAsyncStreamReader<global::Dentalmodeltransfer.ClientMessage> requestStream, grpc::IServerStreamWriter<global::Dentalmodeltransfer.ServerMessage> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DentalModelTransfer</summary>
    public partial class DentalModelTransferClient : grpc::ClientBase<DentalModelTransferClient>
    {
      /// <summary>Creates a new client for DentalModelTransfer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DentalModelTransferClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DentalModelTransfer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DentalModelTransferClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DentalModelTransferClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DentalModelTransferClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Android glasses connect as the client. The C++ side streams model data back
      /// while the client can send requests and acknowledgements on the same RPC.
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Dentalmodeltransfer.ClientMessage, global::Dentalmodeltransfer.ServerMessage> StreamDentalModel(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StreamDentalModel(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Android glasses connect as the client. The C++ side streams model data back
      /// while the client can send requests and acknowledgements on the same RPC.
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Dentalmodeltransfer.ClientMessage, global::Dentalmodeltransfer.ServerMessage> StreamDentalModel(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_StreamDentalModel, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override DentalModelTransferClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DentalModelTransferClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DentalModelTransferBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_StreamDentalModel, serviceImpl.StreamDentalModel).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DentalModelTransferBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_StreamDentalModel, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Dentalmodeltransfer.ClientMessage, global::Dentalmodeltransfer.ServerMessage>(serviceImpl.StreamDentalModel));
    }

  }
}
#endregion
